name: Add Labels to PRs

on:
  pull_request_target:
    types: [opened]
    branches:
      - main
      - develop

jobs:
  add-labels:
    if: false
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Add 'GrabSwagKit' Label to PRs
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const prNumber = context.payload.pull_request.number;
            const label = 'GrabS';

            const addLabelParams = {
                owner: owner,
                repo: repo,
                issue_number: prNumber,
                labels: [label]
            };

            await github.issues.addLabels(addLabelParams);

            console.log(`Added the 'GrabSwagKit' label to PR #${prNumber}.`);
